# Generated by Django 3.1.1 on 2021-05-01 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=50)),
                ('t_type', models.CharField(max_length=50)),
                ('t_cat', models.CharField(max_length=50)),
                ('max_player', models.IntegerField(default=0)),
                ('total_player', models.IntegerField(default=0)),
                ('avl_player', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=150)),
                ('match_time', models.DateTimeField()),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=50)),
                ('pubg_id', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('kill', models.IntegerField(default=0)),
                ('total_earn', models.FloatField(default=0)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
